application-short-name: SAMPLE-APP
application-context-name: /sample-app/api
version: v1
apiUrl: ${application-context-name}/${version}
server:
  port: 8080

app:
  application-context-name: /sample-app/api
  application-short-name: SAMPLE-APP
  repository-query-limit-warning-ms: 10
  default-service-enable-log-request: true
  log-request-http: true
  time-trace-enabled: false
  async-executor-core-pool-size: 1
  async-executor-max-pool-size: 4
  async-executor-keep-alive-seconds: 10
  async-executor-queue-capacity: 50
  datasource:
    default:
      enable: true
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/admindb
      username: root
      password: vinhvove
      configuration:
        idle-timeout: 10000
        minimum-idle: 10
        maximum-pool-size: 50
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQL8Dialect
          temp:
            use_jdbc_metadata_defaults: false
          format_sql: true
          show_sql: true
          use_sql_comments: true
          hbm2ddl:
            auto: none
  cache:
    external:
      enable: true
      applicationShortName: SAMPLE-APP
      delimiter: '::'
      cacheDefaultExpiration: 100800000
      scanLimit: 1000
      cacheExpirations:
        SampleService: 180
        SampleService1: 180
      host: 127.0.0.1
      port: 6379
      username:
      password:
      nodes: 127.0.0.1:6378, 127.0.0.2:6377, 127.0.0.3:6376
      cluster:
        enable: false
      sentinel:
        enable: false
        master: mymaster

spring:
  config:
    import: optional:configserver:http://127.0.0.1:8888
  jpa:
    open-in-view: false
  kafka:
    enabled: false
    bootstrap-servers: http://localhost:9092
    producer:
      enabled: false
      bootstrap-servers: http://localhost:9092
      retries: 3
      queue-size: 100
      request-timeout: 4000
      delivery-timeout: 6000
      default-topic:
    consumer:
      enabled: false

logging:
  level:
    org:
      springframework:
        web:
          filter:
            CommonsRequestLoggingFilter: DEBUG
      hibernate:
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
        SQL: DEBUG
    com:
      company:
        common: DEBUG
      zaxxer:
        hikari:
          HikariConfig: DEBUG

info:
  build:
    description: Sample internal service
    name: my-service
    version: 0.0.1-SNAPSHOT
    artifact: my-service
